version: "3.9"
services:
  trading-engine:
    build: .
    image: trading-engine:latest
    container_name: trading-engine
    environment:
      DEFAULT_PRICE: 20100
      PRICE_FLUCTUATION: 10
      DEFAULT_INDEX: "NIFTY"
      MARKET_CLOSE: "15:20"
